version: 0.0
Resources:
  - myLambdaFunction:
      Type: AWS::Lambda::Function
      Properties:
        Name: "whats-the-workout-api"
        Alias: "whats-the-workout-api-alias"
        CurrentVersion: "1"
        TargetVersion: "2"