version: 0.2

phases:
  install:
    commands:
    - npm install --silent --no-progress -g npm
    - npm install --silent --no-progress -g serverless
  pre_build:
    commands:
    - npm install --silent --no-progress
  build:
    commands:
    - mkdir -p target/prod
    - serverless package --package target/prod --stage prod -v -r us-east-2
    - serverless deploy --stage prod --package target/prod -v -r us-east-2

artifacts:
  files:
  - target/**/*
  - serverless.yml