service: whats-the-workout-api

provider:
  name: aws
  runtime: nodejs12.x
  stage: prod
  region: us-east-2

functions:
  app:
    handler: index.handler
    events:
      - http: ANY /
      - http: 'ANY {proxy+}'
