service: whats-the-workout-api
plugins:
  - serverless-domain-manager

provider:
  name: aws
  runtime: nodejs12.x
  stage: prod
  region: us-east-2

functions:
  app:
    handler: index.handler
    events:
      - http: ANY /
      - http: 'ANY {proxy+}'

custom:
  customDomain:
    domainName: api.whatstheworkout.com
    basePath: ''
    stage: prod
    createRoute53Record: true      